defaults:
  - override hydra/job_logging: custom
  - _self_

base_dataset:
  id: multi-wiki-qa
  organisation: alexandrainst
  split: train
  context_key: context
  question_key: question
  answer_key: answers
  squad_format: true

beta_distribution:
  mean: 0.2
  std: 0.15

hub_organisation: alexandrainst
private: true

testing: false

max_workers: 8

save_dataset_to_file: false

training:
  output_dir: models
  batch_size: 16
  epochs: 5
  learning_rate: 1e-5
  weight_decay: 0.01
  push_to_hub: False
  max_length: 8192

models:
  hallu_detect_model: mmBERT-small
  pretrained_model: jhu-clsp/mmBERT-small
  eval_model: Qwen/Qwen3-0.6B
  hallu_gen_model: gpt-5-mini

language: da

generation:
  max_examples: 1000
  max_new_tokens: 256

manual_check:
  input_path: data/final/multi-wiki-qa-da-Qwen3-0.6B.jsonl
  output_path: data/ground_truth/manual_check_da_Qwen3-0.6B.md
  format: md
  max_rows: -1
  max_chars: 300
  include_context: false
  context_chars: 200

ragtruth:
  path: data/processed/ragtruth_da/ragtruth_data_da.json
  enable: true
enable_wiki: false